Treasure Hunt:
  Min-Players: 3
  Max-Attempts: 50
  Spawn-Radius: 1000
Ability Boost:
  Min-Players: 2
  Duration: 300
FFA:
  Start-Countdown: 60
  Min-Players: 3
  World: FFA
  TeleportLocations:
    - "6,-60,3"
    - "8,-60,-6"
    - "6,-60,-16"
    - "7,-60,-16"
    - "-21,-60,-17"
    - "-23,-60,-5"
    - "-19,-60,6"
    - "-4,-60,7"
FishingContest:
  Time: 10
  Min-Players: 4
  Drop-Chance: 5
TaskEvent:
  Min-Players: 3
  Min-Items: 3
  Max-Items: 7
  Min-Mobs: 1
  Max-Mobs: 5
  TasksAmount: 3
  Time: 5
LootLama:
  Min-Players: 2
  Amount: 3
  Spawn-Chance: 0.4
RandomProjectiles:
  Min-Players: 3
  Time: 5
DoubleOre:
  Min-Players: 2
  Duration: 5