Treasure Hunt:
  Min-Players: 3
  Max-Attempts: 50
  Spawn-Radius: 500
Ability Boost:
  Min-Players: 2
  Duration: 600
FFA:
  Start-Countdown: 60
  Min-Players: 3
  World: FFA
  TeleportLocations:
    - "6,-60,3"
    - "8,-60,-6"
    - "6,-60,-16"
    - "7,-60,-16"
    - "-21,-60,-17"
    - "-23,-60,-5"
    - "-19,-60,6"
    - "-4,-60,7"
FishingContest:
  Time: 5
  Min-Players: 4
TaskEvent:
  Min-Players: 3
  Min-Items: 3
  Max-Items: 7
  Min-Mobs: 1
  Max-Mobs: 12
  TasksAmount: 3
  Time: 5
Soccer:
  Start-Countdown: 60
  Min-Players: 2
  World: Soccer
  TeleportLocations:
    - "6,-60,3"
    - "8,-60,-6"
    - "6,-60,-16"
    - "7,-60,-16"
    - "-21,-60,-17"
    - "-23,-60,-5"
    - "-19,-60,6"
    - "-4,-60,7"
