name: RandomEvents
version: 1.0
main: de.nikey.randomEvents.RandomEvents
api-version: 1.21
authors: [ Nikey ]
website: https://github.com/NikeyV1
commands:
  event:
    description: Start event
  ffa:
    description: FFA command